### ISSUE TITLE
Failure to deliver message when not well connected

### ISSUE THREAD

**Issue by jeanphilippeD** [maidsafe/routing#1727]
At commit 11358bcf27a74d405ceb61711d4a0e2951de360d  we got a soak test seed failure for Reliable Message Delivery.

On this particular seed, the NodeApproval message is sent to the 1st hop, but then that hop try to send it to itself instead of the next hop, and then drop the message as already seen.
This can happen when the relay node is not well connected enough with the next section, then the best section is ourselves.

To fix this we probably need to do a few things:
-Consider all the node we can communicate with (in peer_map) as connected.
-When resending to our section, we probably want to send to all our nodes so if one is better connected it can forward the message.
-These 2 steps were implemented in https://github.com/jeanphilippeD/routing/tree/try_fix_to_silence_issue and were not enough: When resending to our section because not well connected enough we will probably also want to send to any node that we were connected to from the best destination. But we may also want to send to other sections that may be better connected.

Slack chat:
```
Stephen Coyle  4 hours ago
Morning guys, got a new FAILURE in the soak tests for PR 1725 overnight:

---- mock_network::churn::messages_during_churn stdout ----
thread 'mock_network::churn::messages_during_churn' panicked at 'Non-empty set of failed nodes! Failed nodes: [40380d..]', tests/mock_network/churn.rs:613:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

====================================================
Some([1354155478, 1967105506, 274954128, 642718695])
====================================================


Jean-Philippe Dufraigne  1 hour ago
I don't think this is related to this PR 1725.
I am looking at it and it seems to be an RMD issue. (using the latest version of the PR)
Again NodeApproval seem to not be delivered.What we get in the debug message is that the section that has more than 3 connections is ourselves, then we send to ourselves and eventually filter the message out.

DEBUG 12:04:14.858929984 [routing::states::elder mod.rs:1349] Elder(5006bc..(010)): Sending message RoutingMessage { src: PrefixSection(prefix: Prefix(010)), dst: Client { client_name: 40380d.., proxy_node_name: acf68f.. }, content: NodeApproval { GenesisPfxInfo(Prefix(010), gen_version: 22, latest_version: 23) } } via targets [PublicId(name: c922d2..), PublicId(name: cbb972..), PublicId(name: c70a25..), PublicId(name: c2ef9c..), PublicId(name: c39e17..), PublicId(name: df79aa..), PublicId(name: d9a93e..), PublicId(name: d4e486..), PublicId(name: d7243d..), PublicId(name: d70ac9..)]

I was trying to solve that issue before with https://github.com/jeanphilippeD/routing/tree/try_fix_to_silence_issue but it did not completely fix the issue.
I think what I was thinking was missing at the time was we should also add targets from the section that we are not sufficiently connected too as well so the message is delivered.I'll add some logs to clarify what exactly is the connection situation when that happen with this seed.@bart and idea comment on the approach?


Bartłomiej Kamiński:desktop_computer:  1 hour ago

    What we get in the debug message is that the section that has more than 3 connections is ourselves, then we send to ourselves and eventually filter the message out.

I don't really get that, can you elaborate?
The debug message you posted seems to indicate that a sender in section 010 tries to send to 10 (or 101, not sure what sections are there, but the target starts with a, so 1010...) via 110. Not sure what you mean by sending to ourselves?


Jean-Philippe Dufraigne  1 hour ago
You are correct, I pasted the wrong debug line.
The problem occur on the second hop.

DEBUG 12:04:15.174285315 [routing::states::elder mod.rs:1349] Elder(c70a25..(110)): Sending message RoutingMessage { src: PrefixSection(prefix: Prefix(010)), dst: Client { client_name: 40380d.., proxy_node_name: acf68f.. }, content: NodeApproval { GenesisPfxInfo(Prefix(010), gen_version: 22, latest_version: 23) } } via targets [PublicId(name: c922d2..), PublicId(name: cbb972..), PublicId(name: c2ef9c..), PublicId(name: c39e17..), PublicId(name: df79aa..), PublicId(name: d9a93e..), PublicId(name: d4e486..), PublicId(name: d7243d..), PublicId(name: d70ac9..)]

...

DEBUG 12:04:15.282836050 [routing::states::elder mod.rs:553] Elder(c922d2..(110)) Known message: RoutingMessage { src: PrefixSection(prefix: Prefix(010)), dst: Client { client_name: 40380d.., proxy_node_name: acf68f.. }, content: NodeApproval { GenesisPfxInfo(Prefix(010), gen_version: 22, latest_version: 23) } } - not handling further



Bartłomiej Kamiński:desktop_computer:  1 hour ago
I see...
Maybe what we should do would be to ignore who we are connected to? The idea with quic-p2p is that we should be able to make connections on the fly, so maybe if we know that we should be sending to another section, we should just do it and connect as needed? That should also fix the problem, shouldn't it?


Jean-Philippe Dufraigne  1 hour ago
Possibly, but I believe we still need the connection info though, which I don't think we have if we are not connected (so the peer in the peer_map).
I think this is what that commit part of the 2 commit attempt was trying to do, I think: https://github.com/jeanphilippeD/routing/commit/a8fe858980ebf1c574336241b85512c83e03c3f5

            let conn_peers = self
                .peer_map()
                .connected_ids()
                .map(|pub_id| pub_id.name())
                .chain(iter::once(self.name()))
                .collect_vec();

so i still think that if we are not connected to all the nodes we still need to be able to send a RoutingMessage to get their connection info.


Jean-Philippe Dufraigne  32 minutes ago
I'll create an issue for it, it is probably best for me to focus on finishing SharedState first as it is going to block you.

```

**Comment by jeanphilippeD** [comment]
Seed for PR 1726
```
Fast machine failed on iteration 18677

failures:

---- mock_network::churn::messages_during_churn stdout ----
thread 'mock_network::churn::messages_during_churn' panicked at 'Non-empty set of failed nodes! Failed nodes: [cae68a..]', tests/mock_network/churn.rs:613:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

=====================================================
Some([547092002, 3997428567, 1437647140, 3029713186])
=====================================================

Stephen Coyle  5 hours ago
slow machine failed on iteration 8889

failures:

---- mock_network::churn::messages_during_churn stdout ----
thread 'mock_network::churn::messages_during_churn' panicked at 'Non-empty set of failed nodes! Failed nodes: [bfc5de..]', tests/mock_network/churn.rs:613:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

=====================================================
Some([2612287264, 3798105121, 3571571910, 595431060])
=====================================================
```
