### ISSUE TITLE
OS X - simple_key_value_store - thread '<unnamed>' panicked at 'Http11Message lost its underlying stream somehow',

### ISSUE THREAD

**Issue by rossmuir** [maidsafe/routing#633]
Panic on OS X using simple_key_value_store

```
CI-OSX-64:SAFENetwork_examples ci-mac$ ./simple_key_value_store --node
thread '<unnamed>' panicked at 'Http11Message lost its underlying stream somehow', /Users/jenkins/.cargo/registry/src/github.com-0a35038f75765ae4/hyper-0.6.10/src/http/h1.rs:270
```
With RUST_LOG=debug
```
CI-OSX-64:SAFENetwork_examples ci-mac$ RUST_LOG=debug ./simple_key_value_store --node
DEBUG:hyper::net: http scheme
DEBUG:hyper::http::h1: request line: Get "/uyd4tz2eg1i/IGD/upnp/IGD.xml" Http11
DEBUG:hyper::http::h1: headers=Headers { Host: 192.168.1.254:8000, }
DEBUG:hyper::net: http scheme
DEBUG:hyper::http::h1: request line: Get "/RootDevice.xml" Http11
DEBUG:hyper::http::h1: headers=Headers { Host: 192.168.0.1, }
DEBUG:hyper::client::response: version=Http11, status=Ok
DEBUG:hyper::client::response: headers=Headers { Content-type: text/xml, Expires: Thu, 3 Oct 1968 12:00:00 GMT, Connection: close, Pragma: no-cache, Content-Length: 2892, }
DEBUG:hyper::net: http scheme
DEBUG:hyper::client::response: version=Http10, status=Ok
DEBUG:hyper::client::response: headers=Headers { Expires: -1, Content-Type: text/xml, Cache-Control: no-cache, }
DEBUG:hyper::http::h1: request line: Post "/WANIPConnection" Http11
DEBUG:hyper::http::h1: headers=Headers { Content-Length: 790, SOAPAction: "urn:schemas-upnp-org:service:WANIPConnection:1#AddPortMapping", Host: 192.168.0.1, }
thread '<unnamed>' panicked at 'Http11Message lost its underlying stream somehow', /Users/jenkins/.cargo/registry/src/github.com-0a35038f75765ae4/hyper-0.6.10/src/http/h1.rs:270
INFO:routing::routing_node: RoutingNode Client(9004fd..414d53) listens on [Tcp(V4(192.168.1.69:5483)), Tcp(V4(192.168.0.20:5483))]
DEBUG:routing::routing: started routing run()
DEBUG:routing::routing_node: RoutingNode started running and started bootstrap```

**Comment by rossmuir** [comment]
For reference https://github.com/maidsafe/crust/issues/262

**Comment by benjaminbollen** [comment]
I can close this issue, as it is not a routing issue
